/* ****************************************************************************
 * Copyright 2026 51 Degrees Mobile Experts Limited (51degrees.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 * ***************************************************************************/

use std::fmt;
use std::str::FromStr;

use base64::engine::general_purpose::GeneralPurpose;
use base64::engine::{DecodePaddingMode, GeneralPurposeConfig};
use base64::{alphabet, engine::Engine as _};
use chrono::{DateTime, Utc};

use crate::crypto::Crypto;
use crate::error::{Error, Result};
use crate::io;
use crate::version::Version;

/// Base 64 engine that writes the standard alphabet with padding, and reads
/// strings with or without padding. Encoded OWIDs occur both with and
/// without padding, so reading must accept both.
const BASE64: GeneralPurpose = GeneralPurpose::new(
    &alphabet::STANDARD,
    GeneralPurposeConfig::new().with_decode_padding_mode(DecodePaddingMode::Indifferent),
);

/// OWID structure which can be used as a node in a tree.
///
/// An OWID records that the processor operating the domain handled the
/// payload, and any other OWIDs covered by the signature, at the date and
/// time given. Once signed it is immutable. Any change to the fields will
/// cause verification to fail.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Owid {
    /// The byte version of the OWID.
    pub version: Version,
    /// Domain associated with the creator.
    pub domain: String,
    /// The date and time to the nearest minute in UTC of the creation.
    pub date: DateTime<Utc>,
    /// Array of bytes that form the payload.
    pub payload: Vec<u8>,
    /// Signature for this OWID and any others provided when signing.
    /// Generated by the [`crate::Creator`] instance.
    pub signature: Vec<u8>,
}

impl Default for Owid {
    fn default() -> Self {
        Owid {
            version: Version::default(),
            domain: String::new(),
            date: Utc::now(),
            payload: Vec::new(),
            signature: Vec::new(),
        }
    }
}

impl Owid {
    /// Creates a new unsigned OWID with the domain, date, and payload
    /// provided and the current version.
    pub fn new(domain: &str, date: DateTime<Utc>, payload: Vec<u8>) -> Self {
        Owid {
            version: Version::default(),
            domain: domain.to_owned(),
            date,
            payload,
            signature: Vec::new(),
        }
    }

    /// Creates an OWID from a base 64 encoded string.
    ///
    /// # Errors
    ///
    /// Returns [`Error::Base64`] if the string is not valid base 64, or any
    /// error from [`Owid::from_byte_array`].
    ///
    /// # Examples
    ///
    /// ```
    /// use owid::{Creator, Crypto, Owid};
    ///
    /// let creator = Creator::new("example.com", Crypto::new()).unwrap();
    /// let original = creator.sign_string("Hello World").unwrap();
    /// let copy = Owid::from_base64(&original.as_base64().unwrap()).unwrap();
    /// assert_eq!(original.payload, copy.payload);
    /// ```
    pub fn from_base64(value: &str) -> Result<Self> {
        Owid::from_byte_array(&BASE64.decode(value)?)
    }

    /// Creates an OWID from its binary form.
    ///
    /// # Errors
    ///
    /// Returns [`Error::UnsupportedVersion`] if the first byte is not a
    /// known version, or [`Error::UnexpectedEndOfBuffer`] if the buffer is
    /// too short for the remaining fields.
    pub fn from_byte_array(buffer: &[u8]) -> Result<Self> {
        let mut reader = io::Reader::new(buffer);
        Owid::from_reader(&mut reader)
    }

    /// Creates an OWID by reading the next fields from the reader.
    pub(crate) fn from_reader(reader: &mut io::Reader<'_>) -> Result<Self> {
        let version = Version::try_from(reader.read_byte()?)?;
        if version == Version::Empty {
            return Ok(Owid {
                version,
                ..Owid::default()
            });
        }
        Ok(Owid {
            version,
            domain: reader.read_string()?,
            date: reader.read_date(version)?,
            payload: reader.read_byte_array()?,
            signature: reader.read_signature()?,
        })
    }

    /// Returns the OWID as a byte array.
    ///
    /// # Errors
    ///
    /// Returns [`Error::InvalidSignatureLength`] if the OWID has not been
    /// signed, or other errors if the fields can not be encoded.
    pub fn as_byte_array(&self) -> Result<Vec<u8>> {
        let mut buffer = Vec::new();
        self.to_buffer(&mut buffer)?;
        Ok(buffer)
    }

    /// Returns the OWID as a base 64 encoded string.
    ///
    /// # Errors
    ///
    /// See [`Owid::as_byte_array`].
    pub fn as_base64(&self) -> Result<String> {
        Ok(BASE64.encode(self.as_byte_array()?))
    }

    /// Appends the OWID, including the signature, to the buffer provided.
    ///
    /// # Errors
    ///
    /// See [`Owid::as_byte_array`].
    pub fn to_buffer(&self, buffer: &mut Vec<u8>) -> Result<()> {
        self.to_buffer_no_signature(buffer)?;
        io::write_signature(buffer, &self.signature)
    }

    /// Writes an empty OWID marker. Used to indicate optional OWIDs in byte
    /// arrays.
    pub fn empty_to_buffer(buffer: &mut Vec<u8>) {
        io::write_byte(buffer, Version::Empty.as_byte());
    }

    /// Appends the fields other than the signature to the buffer. This is
    /// the data over which the signature is calculated.
    pub(crate) fn to_buffer_no_signature(&self, buffer: &mut Vec<u8>) -> Result<()> {
        io::write_byte(buffer, self.version.as_byte());
        io::write_string(buffer, &self.domain)?;
        io::write_date(buffer, &self.date, self.version)?;
        io::write_byte_array(buffer, &self.payload)
    }

    /// Builds the byte array used for signing and verification. Contains the
    /// fields of this OWID without the signature, followed by the complete
    /// byte form of each of the others in the order provided.
    pub(crate) fn data_for_crypto(&self, others: &[&Owid]) -> Result<Vec<u8>> {
        let mut buffer = Vec::new();
        self.to_buffer_no_signature(&mut buffer)?;
        for other in others {
            other.to_buffer(&mut buffer)?;
        }
        Ok(buffer)
    }

    /// The payload interpreted as a string. Bytes that are not valid UTF-8
    /// are replaced with the replacement character.
    pub fn payload_as_string(&self) -> String {
        String::from_utf8_lossy(&self.payload).into_owned()
    }

    /// The payload as lower case hexadecimal for display purposes.
    pub fn payload_as_printable(&self) -> String {
        self.payload.iter().map(|b| format!("{b:02x}")).collect()
    }

    /// The payload as a base 64 encoded string.
    pub fn payload_as_base64(&self) -> String {
        BASE64.encode(&self.payload)
    }

    /// Returns the number of complete minutes that have elapsed since the
    /// OWID was created. The granularity is to the nearest minute.
    pub fn age_minutes(&self) -> i64 {
        (Utc::now() - self.date).num_minutes()
    }

    /// Verifies this OWID, and any others that were included when it was
    /// signed, using the crypto instance provided.
    ///
    /// Pass an empty slice for `others` when the OWID was signed on its own.
    ///
    /// # Errors
    ///
    /// Returns [`Error::KeyMissing`] if the crypto instance can not verify,
    /// or other errors if the fields can not be encoded.
    ///
    /// # Examples
    ///
    /// ```
    /// use owid::{Creator, Crypto};
    ///
    /// let crypto = Crypto::new();
    /// let creator = Creator::new("example.com", crypto.clone()).unwrap();
    /// let owid = creator.sign_string("Hello World").unwrap();
    /// assert!(owid.verify_with_crypto(&crypto, &[]).unwrap());
    /// ```
    pub fn verify_with_crypto(&self, crypto: &Crypto, others: &[&Owid]) -> Result<bool> {
        let data = self.data_for_crypto(others)?;
        crypto.verify_byte_array(&data, &self.signature)
    }

    /// Verifies this OWID, and any others that were included when it was
    /// signed, using the public key in SPKI PEM form provided.
    ///
    /// # Errors
    ///
    /// Returns [`Error::Key`] if the PEM is not a valid public key, or any
    /// error from [`Owid::verify_with_crypto`].
    pub fn verify_with_public_key(&self, public_pem: &str, others: &[&Owid]) -> Result<bool> {
        let crypto = Crypto::new_verify_only(public_pem)?;
        self.verify_with_crypto(&crypto, others)
    }
}

impl fmt::Display for Owid {
    /// Formats the OWID as a base 64 string, or the text of the error if it
    /// can not be encoded.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.as_base64() {
            Ok(value) => write!(f, "{value}"),
            Err(e) => write!(f, "{e}"),
        }
    }
}

impl FromStr for Owid {
    type Err = Error;

    fn from_str(s: &str) -> Result<Self> {
        Owid::from_base64(s)
    }
}

impl TryFrom<&[u8]> for Owid {
    type Error = Error;

    fn try_from(value: &[u8]) -> Result<Self> {
        Owid::from_byte_array(value)
    }
}
